### ISSUE TITLE
CCured running issue with GNU Coreutils Datasets

### ISSUE THREAD

**Issue by Hanseltu** [Lightninghkm/DataGuard#1]
Hi, thanks for your nice implementation of `ccured` to be an LLVM pass!

May I ask what kinds of test programs are currently supported by `ccured`'s analysis? I have tried to run it with a widely-used dataset ([GNU Coreutils](https://www.gnu.org/software/coreutils/)), but it seems `ccured` fails to analyze the whole program and interpret during the analysis.

I didn't try all test programs in the dataset for now, but I have taken `ls` and `cat` test programs for example and they all make `ccured` fail to complete the analysis. Please see the following outputs:

```
$./run-cat.sh
....... (omit the printing stuff)

Wrong types for attribute: inalloca nest noalias nocapture nonnull readnone readonly signext sret zeroext byval dereferenceable(1) dereferenceable_or_null(1)
{ i8*, i64 } (i64)* @xmalloc_nesCheck
in function xmalloc_nesCheck
LLVM ERROR: Broken function found, compilation aborted!

$./run-ls.sh
....... (omit the printing stuff)

Instruction does not dominate all uses!
  %62 = load i64, i64* %_size_nesCheck1, !dbg !4318
  store i64 %62, i64* %_size_nesCheck8, !dbg !4440
inlinable function call in a function with debug info must have a !dbg location
  call void @setMetadataTableEntry(i64 ptrtoint ([24 x %struct.bin_str]* @color_indicator to i64), i64 384, i64 116175280)
inlinable function call in a function with debug info must have a !dbg location
  call void @setMetadataTableEntry(i64 ptrtoint ([24 x %struct.bin_str]* @color_indicator to i64), i64 384, i64 116175280)
inlinable function call in a function with debug info must have a !dbg location
  call void @setMetadataTableEntry(i64 ptrtoint ([24 x %struct.bin_str]* @color_indicator to i64), i64 384, i64 116175280)
inlinable function call in a function with debug info must have a !dbg location
  call void @setMetadataTableEntry(i64 ptrtoint ([24 x %struct.bin_str]* @color_indicator to i64), i64 384, i64 116175280)
inlinable function call in a function with debug info must have a !dbg location
  %262 = call i64 @lookupMetadataTableEntry(i64 %261)
inlinable function call in a function with debug info must have a !dbg location
  %264 = call i64 @lookupMetadataTableEntry(i64 %263)
inlinable function call in a function with debug info must have a !dbg location
  %266 = call i64 @lookupMetadataTableEntry(i64 %265)
inlinable function call in a function with debug info must have a !dbg location
  %268 = call i64 @lookupMetadataTableEntry(i64 %267)
in function parse_ls_color
LLVM ERROR: Broken function found, compilation aborted!
```
Please find the reproduced files here: 
[running-issue.zip](https://github.com/Lightninghkm/DataGuard/files/8308842/running-issue.zip)

For the running environment, I run the experiments on a ubuntu 18.04 system, and all test programs, including the `ccured` (and its pgd and SVF libraries) and GNU Coreutils, are compiled under LLVM-10, so it couldn't be the compatibility from compilers.

By the way, I have commented `identifyDifferentKindsOfUnsafePointers` function when I build the `ccured`, as what I want is the marking part of your `ccured`, i.e., I only want to know what kind of type is held by a pointer in the LLVM IR. For the unsafe pointer checking part, I may think about using other solutions to solve it.

Could please take a look when you are available? Is it possible to support analyzing this dataset (or other large-scale test programs) and marking corresponding pointer types based on your implementation? (If you want to test other test programs as well, please let me know, I am happy to share those test programs with you.)

 Thank you so much for your time and looking forward to your reply!

Best regards,
Haoxin

**Comment by Lightninghkm** [comment]
Hi Haoxin,

Thanks for your interest in this framework, I'm so glad that you want to apply the analysis from DataGuard to your ongoing research!

From your description of the "issue", I can see that the CCured analysis actually works on your side. The information you wanted was in the "printing stuff". Maybe it's kind of too long to recognize the important information, and sorry for not explaining it in detail previously in ``README``, I will illustrate it below.

Attached are the 2 output files from my side of the 2 linked bc files that are provided by you. Let's take ``cat`` as an example.
[coreutilout.zip](https://github.com/Lightninghkm/DataGuard/files/8308898/coreutilout.zip)

Please take a look at line 16,762, where it shows the output of the CCured analysis, i.e., the "marking" part of CCured that you wanted.

```
STATS SUMMARY: 
Found 119 functions.
Found 1904 pointer variables:
-->) TOTAL Safe pointer variables:	1690 (88.7605%)
-->) TOTAL Seq pointer variables:	193 (10.1366%)
-->) TOTAL Dyn pointer variables:	21 (1.10294%)
```

Also, at line 17,657, you can also get the number of unsafe pointers on the stack.

```
Total Unsafe Stack Pointer Number by CCured: 68
Total Stack Seq Pointer Number: 64
Total Stack Dyn Pointer Number: 4
```

To generate such output files, you need to slightly change your command, add ``2>&1`` at the end to force the output to the file, not to the command-line interface.

```
opt -o cat.opt.bc -load ../../../libnescheck.so -nescheck -stats -time-passes < cat.linked.bc > cat.nescheckout 2>&1
```

The error you got from the CCured analysis, i.e., ``LLVM ERROR: Broken function found, compilation aborted!`` is not related to and does not affect the static analysis of CCured. As said in the ``README``, we build the CCured analysis based on the previous work ``nesCheck``, this part is related to the runtime enforcement of ``nesCheck``, i.e., generating the instrumented binary given the classification of CCured static analysis. Since we do not need the runtime protection of ``nesCheck`` but only the "marking" part of the CCured static analysis, we didn't dig into this issue too much. But we suspect that it is due to the compatibility issue, e.g., some customized memory allocation function is not handled. Since ``nesCheck`` works with embedded programs on TinyOS, there are definitely some functions on Linux that are not handled. But again, that only affects runtime, not CCured static analysis, and that error message is only issued after static analysis is finished.

Also, please note that the output files above are produced by combining CCured and value-range analysis, the usage of only running CCured analysis is the same. We applied value-range analysis on top of the CCured analysis results, which is similar to what you want to do and demonstrates that it is feasible.

If you want to directly use the classification of CCured for your second-stage analysis, you can refer to the usage of line 1439-1444 in ``NesCheck.cpp``.

Moreover, you do not need to comment out ``identifyDifferentKindsOfUnsafePointers`` as of now, we have already provided the fast version of nesCheck named ``NesCheckFast.cpp`` in the same directory, you can change the ``CMakeLists`` to use that file instead of ``NesCheck.cpp``.

We have tested the whole DataGuard framework on SPEC CPU 2006 benchmark, 5 server programs (i.e., nginx, httpd, proftpd, openvpn, and opensshd), Darpa CGC binaries, Binutils, and Coreutils. So it should be working with most of the user-space programs.

Hope this helps to solve the issue, please feel free to let me know if you have further questions!

Best regards,
Kaiming.

**Comment by Hanseltu** [comment]
Hi Kaiming,

Thank you very much for your super speedy response and insightful comments! Your clarification really makes sense to me!

I am so sorry this kind of "issue" came from my wrong usage/understanding of the tool, which takes up your time and makes some noise to you, I hope you don't mind that :-). I am also so glad to hear the whole `DataGuard` has already been supported for testing broad datasets for now! I will dig deeper into the source code of the `ccured` to see how to combine it with my current study.

Thank you again for your kind help and have a good weekend!

Best regards,
Haoxin

**Comment by Hanseltu** [comment]
Hi, Kaiming,

May I ask a few further questions for you?  Which version of Coreutils did you test before? I was testing in a quite new version, which is Coreutils-9.0, and found that some of the packages (I have tested `chgrp`, `chcon`, `chmod`, and `chown`) make `ccured` get stuck when analyzing. From the outputs emitted by `ccured`, all of those packages yield the same message `empty di local var: quoting_options_from_style1 - 1` at a very early stage and then stop analysis. I am not sure whether this is something related to the root cause of the issue. What could be the problem here?

Please check `chcon.bc` here:
[chcon.bc.zip](https://github.com/Lightninghkm/DataGuard/files/8309325/chcon.bc.zip)


Thanks in advance!
Haoxin

**Comment by Lightninghkm** [comment]
Hi Haoxin,

No problem at all! Please feel free to contact me with anything you want to ask about this repo.

I tested V8.32 on their Github repo. However, I don't think the version of coreutils will affect the analysis.

The message ``empty di local var: quoting_options_from_style1 - 1`` is issued at the stage of generating PDG and SVF graph, and it is from their code that is not maintained by us. But I can confirm that this message will not affect the analysis of CCured.

Also, I recognized that the generation of PDG and SVF graph were slow from my side of the bitcode ``chcon.bc`` that you provided, we have also encountered this situation when we analyzed ``bzip2``. But they are pretty quick on some larger benchmarks, thus, we think this it not related to the code size but must be some patterns of the code that trigger the generation to be slow. Since the PDG and SVF is not the contribution of this work, we did not try to fix it. We have already notified the author of the PDG work about this issue and hopefully he will release a fix when he gets sometime.

I tested the same bitcode you sent (did you link it to ``neschecklib.bc``?) and did not observe the analysis stopped as you described, the analysis finished normally after waiting for the generation of PDG and SVF for a while (10 mins). I have attached the output file below for your convenience, I would suggest you to wait for a bit longer and see what happens on your side.
[chcon.zip](https://github.com/Lightninghkm/DataGuard/files/8309726/chcon.zip)

Best regards,
Kaiming.

**Comment by Hanseltu** [comment]
Hi Kaiming,

Thanks for your helpful reply! It's indeed can work on my machine although it may take a longer time to complete the analysis. I was running other experiments in my machine, and it takes roughly 15min to finish the analysis, so I wrongly thought that `ccured` gets stuck. No further confusion from me now, and thank you so much again!

Best regards,
Haoxin

**Comment by Lightninghkm** [comment]
Hi Haoxin,

You are welcome!

Yes, for a few benchmarks, we do recognize that it costs longer for PDG generation. And again, such delay is not relevant to the size of the bitcode being analyzed. After finishing the PDG and SVF phase, the analysis of CCured is usually fast, for example, the CCured analysis of chcon only takes 32 seconds on my side.

We will keep you updated through this channel if further improvements are made towards generating PDG, please stay tuned!

Best regards,
Kaiming.
