### ISSUE TITLE
Is it possible to get the exact mapping between un-linked IR and linked IR?

### ISSUE THREAD

**Issue by Hanseltu** [Lightninghkm/DataGuard#2]
Hi Kaiming,

Congratulations on your awesome paper on NDSS'22! I have learned a lot from it!

Here, may I ask a further question related to Ccured you implemented? Thanks! My initial goal is to combine a type inference system (e.g.,Ccured) with symbolic execution engines (e.g., KLEE) to help speed up the execution process, motivated by the truth that modern symbolic executors treat all memory addresses to be equal and thus leading to many redundant and un-necessary memory checking. More specifically, I aim to analyze whether an address written to in a `store` instruction or an address read from in a `load` instruction can be *SAFE* or not. Here, the first step is to leverage your Ccured to differentiate different types of pointers on LLVM IR, but I encountered some issues when I tried to accomplish the goal.

The issue comes from the unmapped LLVM IR between the unlinked (linked with `neschecklib.bc`) `bc` file executed by KLEE and the linked `bc` file (handled in Cccured). Ideally, every instruction processed by the function`processInstruction` in the lined `bc` file should have its corresponding instruction in the unlinked version of the `bc` file, but I can not easily find the mapping after digging into the current implementation. Is it possible to do so in your opinion? If yes, how can I make it?

I have also tried to use the number of `store/load` instructions in the unlinked and linked versions of `bc` file to find the relationship, holding the assumption that the processed number of `store/load` instructions should be the same in two `bc` files although the exact instruction information is not the same. However, the assumption seems can only work on simple cases but it is not valid for larger test programs, e.g., `ls` in Coreutils (see more details below). Do you think such an assumption is always valid or there is something wrong when handling the larger test programs on Ccured side? I know such an idea may not be a good solution and it is could be better to find the exact relationships between the two versions of `bc` files.

```
$klee-ccured/examples/ccured/ccured-test/simple-case$ grep load target-test.ll | wc -l
11
$klee-ccured/examples/ccured/ccured-test/simple-case$ grep store target-test.ll | wc -l
10
$klee-ccured/examples/ccured/ccured-test/simple-case$ grep "(~)" target-test.nescheckout | wc -l
21

$klee-ccured/examples/ccured/ccured-test/coreutils$ grep store ls.ll | wc -l
3956
$klee-ccured/examples/ccured/ccured-test/coreutils$ grep load ls.ll | wc -l
7716
$klee-ccured/examples/ccured/ccured-test/coreutils$ grep "(~)" target-test.nescheckout | wc -l
12032
```
Here are some of the files I used:
[ccured-test.zip](https://github.com/Lightninghkm/DataGuard/files/8457101/ccured-test.zip)

Thanks and Best regards,
Haoxin

**Comment by Lightninghkm** [comment]
Hi Haoxin,

Thanks! It is great to see that you have been trying to leverage the ``CCured`` analysis on your research project! Yes, large-scale symbolic execution on real-world programs can suffer, and in our [NDSS 2022](https://www.ndss-symposium.org/ndss-paper/auto-draft-212/) work we also leveraged the results of static analyses to guide the symbolic execution. The idea of "guided" or "selective" symbolic execution has been employed by a lot of previous works such as [Driller](https://sites.cs.ucsb.edu/~vigna/publications/2016_NDSS_Driller.pdf) and [UBITect](cs.ucr.edu/~csong/fse20-ubitect.pdf).

The short answer to your question is, it is not caused by the link/unlink through ``neschecklib.c``, it is due to the fact that the CCured analysis pass will instrument and rewrite the program at the bitcode IR level.

The functionality of ``neschecklib.c`` is for setting, propagating, and extracting metadata constraints (e.g., size constraints), it will not change the original IR, just allocating and processing the metadata structure for the corresponding variables. You can also try to run ``CCured`` on the unlinked bitcode, you will encounter the same scenario - more load/store than original.

Let me give you an example, take a look at line 3155-3163 of the ``target-test.nescheckout`` for ``ls`` provided by you.
```
[0x469e118] (~)   %18 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !1317, !tbaa !1293
	Getting VarInfo for map_prog[0x4696fd8]... found.
	=> Size of map_prog[0x4696fd8] set to   %18 = load i64, i64* %map_prog_size_nesCheck, !dbg !1317
SAFE 
	=>(Register) Classified [0x469e118] as SAFE
	=> Ignored classification of [0x469e118] as SAFE
This is the information for load instruction 	
     SAFE
       %19 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !1317, !tbaa !1293
```

I believe the last 3 lines are added by you for your analysis. The load instruction ``%18 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !1317, !tbaa !1293`` is the original instruction in the ``ls`` program, and it is classified as safe. However, when you tried to print this safe load instruction out, it is changed to ``%19 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !1317, !tbaa !1293``.

What is the difference? Only ``%18`` is changed to ``%19``, while all the other content of the instruction remains the same.

Why does this happen? Take a look at line 667 of ``NesCheck.cpp``, since the original IR instruction does not carry the information of ``explictsizevariable``, and it is needed by the analysis, a new "identical" ``load`` instruction with the information of ``explictsizevariable`` is created and added next to the original instruction. And the analysis will use the new instruction instead of the original one from now on. 

There are also many other kinds of instrumentations in ``NesCheck.cpp``, search for ``Builder->Create``. Again, the new instructions always have the same functionality as the original instructions, i.e., the instrumentation will not change the behavior of the original program.

Then after the instrumentation, the ``Reclassification Propagation`` intrinsic will re-analyze the functions infected by the classification change of global variable. If the being re-analyzed function happens to contain instrumented new load/store instructions (not the case for the above example but you should be able to find one that is very similar), you will observe that the number of load/store instructions being analyzed (by grepping "(~)" as you did) is larger than the number of original load/store instruction, since the newly instrumented instructions are also analyzed.

You can take advantage of the dbg information to create the mapping from the original instruction to the new instruction, in this example, they both have ``!dbg 1317``.

If you don't want the ``Reclassification Propagation`` intrinsic (which will affect the results a bit), you can use the ``NesCheckFast.cpp`` (and un-comment the ``PTAWrapper.*`` in ``CMakeLists.txt``). In this case, you will observe the number of "(~)" be less than or equal to "load" + "store", due to the ``Whitelist Function`` functionality in ``CCured``.

Except for the instrumentation, I just want you to know there are also other reasons for the changes in the IR. For example, the function signature will be rewritten, see ``rewriteFunctionSignature``. PDG and SVF will also change the original IR. But those should not affect your analysis at this stage if you are only looking for load and store instruction, would be better to know this in advance :->

Instead of using the debug location information, maybe you wonder "Can I just remove the instrumentation and rewriting?" Based on my experience, the results would differ for some of the programs while remaining the same for others. If the differences in the results after removal does not matter to your analysis, you can remove them.

Hope this helps, let me know if you have further questions.

Best,
Kaiming.

**Comment by Hanseltu** [comment]
Hi Kaiming,

Thanks for your quick response again!

Yeah, I also realized that the IR will be modified during analysis after instrumentation, which causes the unmapping relationships between the two versions of IR code.  I was wrongly thinking the instrumentation was implemented by linking the `neschecklib.bc`, so I am sorry for my misunderstanding here.

Regarding the solution you provided (using debug information to locate the corresponds), I guess it may not work as well. From your suggestions,

* I believe the last 3 lines are added by you for your analysis. The load instruction `%18 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !1317, !tbaa !1293` is the original instruction in the ls program, and it is classified as safe. However, when you tried to print this safe load instruction out, it is changed to `%19 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !1317, !tbaa !1293`.

Yes, the last 3 lines are indeed produced from my debugging code, and the problem here is that the load instruction `%18 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !1317, !tbaa !1293` is ***not*** the original instruction in the `ls` program. I searched for the relevant instructions that may correspond to the instruction analyzed by Ccured, and here are the results:
```
$klee-ccured/examples/ccured/ccured-test/coreutils$ grep "map_prog" ls.ll 
  %map_prog = alloca %struct.infomap*, align 8
  %4 = bitcast %struct.infomap** %map_prog to i8*, !dbg !8998
  call void @llvm.dbg.declare(metadata %struct.infomap** %map_prog, metadata !8989, metadata !DIExpression()), !dbg !8999
  store %struct.infomap* %arraydecay, %struct.infomap** %map_prog, align 8, !dbg !8999, !tbaa !1289
  %5 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !9002, !tbaa !1289
  %8 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !9007, !tbaa !1289
  %11 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !9010, !tbaa !1289
  store %struct.infomap* %incdec.ptr, %struct.infomap** %map_prog, align 8, !dbg !9010, !tbaa !1289
  %12 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !9012, !tbaa !1289
  %14 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !9017, !tbaa !1289
  %26 = bitcast %struct.infomap** %map_prog to i8*, !dbg !9040
!8989 = !DILocalVariable(name: "map_prog", scope: !8978, file: !1614, line: 647, type: !8990)
```
And `!dbg !1317` is actually mapped to another instruction

```
$klee-ccured/examples/ccured/ccured-test/coreutils$ grep "1317" ls.ll 
  store i32 %call2, i32* %i, align 4, !dbg !1317, !tbaa !1284
(omit un-relevant instructions)
```

From the results, I guess it should have a correspondence of a load instruction in the original `ls` program to a load instruction analyzed by Ccured, but I can not tell which is the exact one.  Do you have any ideas or did I miss something here?

Thanks for your time again in helping me address the issue!

Best regards,
Haoxin

**Comment by Lightninghkm** [comment]
Hi Haoxin,

The load instruction corresponds to the ``%12 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !9012, !tbaa !1289`` in the original ``ls.ll``, as you can see the differences are the resulting SSA variable name (i.e., ``%12`` -> ``%18`` ), and the dbg location identifier (i.e., ``!9012`` -> ``!1317``).

You definitely cannot find an identical instruction in the original ``ls. bc`` of the load instruction ``%18 = load %struct.infomap*, %struct.infomap** %map_prog, align 8, !dbg !1317, !tbaa !1293`` in the instrumented bitcode. The reason is that there are many instructions are rewritten before this load instruction, based on the naming policy of the LLVM SSA variable, the name of the resulting SSA variable of this load instruction would definitely differ from the original one. If you are not familiar with the SSA naming, check out LLVM [LangRef](https://llvm.org/docs/LangRef.html), [MemorySSA](https://llvm.org/docs/MemorySSA.html), and this [Link](https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/control-structures/ssa-phi.html).

In the previous reply, I wrote "You can take advantage of the dbg information to create the mapping from the original instruction to the new instruction, in this example, they both have ``!dbg 1317``."  This is for determining, in the **instrumented program**, whether an instrumented load instruction (i.e., ``%19``) maps to an original load instruction (i.e., ``%18``). It is not for determining whether an instrumented load instruction (i.e., ``%19``) in the **instrumented program** maps to an original load instruction (i.e., ``%12``) in the **original program** (i.e., ``ls.ll``).

Why is that? Because the program is instrumented and rewritten, the dbg location information identifier will definitely change during this process, since we are creating the new instrumented bitcode for the original program. That's why you observe the change of ``!9012`` -> ``!1317``

However, though the identifier changes, the information encoded behind the identifier remains the same (e.g., filename, function name, and line number of this variable). If you are not familiar with extracting such information by leveraging dbg location information, check this [doc](https://llvm.org/docs/SourceLevelDebugging.html) and the [llvm::DebugLoc](https://llvm.org/doxygen/classllvm_1_1DebugLoc.html) class. Pay attention to the name change of functions and variables since the CCured pass will add ``_nesCheck`` after instrumentation.

Also, I would like to inform you that due to the instrumentation, the debug information of a few variable will be corrupted (a known bug) and in that case you will need to refer to the APIs in [llvm::Instruction](https://llvm.org/doxygen/classllvm_1_1Instruction.html) class to pinpoint them.

In our following analysis, we get rid of this problem by performing incremental analysis based on the instrumented bitcode after the ``CCured`` analysis, I would recommend you do so as well. 

If the mapping to the original bitcode is required and necessary for your analysis, then you probably should try to remove those instrumentation and rewriting from our current ``CCured`` pass while preserving the functionality. Since it is beyond the scope of our existing work and will potentially affect the results of the analysis, we do not have the plan to release that version. Feel free to try to play with the ``CCured`` pass and initiate a PR on that!

Best,
Kaiming.

**Comment by Hanseltu** [comment]
Hi Kaiming,

Thanks for your speedy reply!

Ok, your clarification really makes sense to me. I think the idea of using the information encoded behind the identifier should work for me.  I may use `filename+function name+line number of a statement+column number of a statement`(adding the column number as well to avoid the noise that one line statement in source code may be translated to multiply store/load instructions in IR code) in source code to construct the mapping.

For the more design and implementation details in `Ccured` pass, let me play with it further and see whether a PR is needed. I will let you know if I have any progress!

I just close this issue and thank you so much again for your kind help!

Best Regards,
Haoxin
