### ISSUE TITLE
A few questions about Ccured and SAFECode

### ISSUE THREAD

**Issue by Hanseltu** [Lightninghkm/DataGuard#3]
Hi,

Thanks for your impressive work again. May I ask a few more questions about some details on implementing Ccured and SAFECode? My initial goal here is to find a solution to extend DataGuard to support the classification of both heap and global objects as well.

* About Ccured. I checked more about the current Ccured implementation, and I think here is the code handling heap objects (if I understand correctly): https://github.com/Lightninghkm/DataGuard/blob/master/CCured/NesCheckFast.cpp#L1241. Inside this if-branch, the `isUnsafeStackPointer` is assigned as `false`, and the branch will execute `break` later. Does this mean the current version of DataGuard treats all heap objects as safe objects? And for global objects (https://github.com/Lightninghkm/DataGuard/blob/master/CCured/NesCheckFast.cpp#L1294), are they also classified as safe? I raised the questions as I am not sure whether the current implementation of Ccured already supports classifying all (stack, heap, and global) objects or whether DataGuard just simply filters heap or global objects because the paper is only targeting the data on the stack. Thanks!

* About SAFECode. I am sorry I didn't find any implementation details about SAFECode in the paper. Did you use the version here ([https://safecode.cs.illinois.](https://safecode.cs.illinois.edu/)[edu](https://safecode.cs.illinois.edu/)[/](https://safecode.cs.illinois.edu/)) to support the pointers analysis? Since the supported LLVM versions are quite old (used on LLVM-3.x), I am not sure how did you use it in DataGuard (used on LLVM-10). Could you please let me know it? Also, I am also concerned about whether SAFECode supports classifying the pointers in the heap or global. Do you have any ideas about it? Thanks!

* About challenges for classifying the pointers from the heap. Currently, I am confused about what are the difference between classifying heap objects and stack objects, because the pointers whether point to the stack or heap is a value. The locations of that value may not matter a lot, so I don't see any differences/challenges to classify the heap objects. Did I miss anything? Do you have any ideas on what could be the specific challenges to identify the unsafe pointer operations from the heap or global instead of the stack? Thanks!

Thank you so much if can give me some hints on the above questions. Have a nice week ahead!

Best regards,
Haoxin

**Comment by Lightninghkm** [comment]
Hi Haoxin,

Thanks for your interest.

The DataGuard work targets the stack, so we only analyze the cases where "pointers are on the stack and point to the stack".

Stack pointers that point to heap and globals are filtered out in the CCured analysis stage to exempt them from further static analyses (e.g., value range analysis). This means CCured can handle them but we filtered them out. They are not classified as safe but directly classified as unsafe. They are not counted as unsafe stack pointers since our additional analyses require the pointer points to the stack.

We did not use SAFECode in DataGuard, but I tested SAFECode in our follow-up works for comparison, I used the same repo pointed out by you.

There are plenty of differences between analyzing stack and heap objects, at implementation-wise, you don't see heap/global objects represented as SSA variables in LLVM IR, but as memory locations, which is different from stack objects. Pointer-wise, they are pretty much the same (e.g., ptrarith and cast are the same), so the current CCured classification can already handle them.

We have a new work currently under submission for heap protection using a similar spirit, please stay tuned.

Best,
Kaiming.

**Comment by Hanseltu** [comment]
Hi Kaiming,

Thank you so much for your super speedy responses. Your explanations cleared my confusions.

Wish the best for your new submission and hope I can read it soon!


Best,
Haoxin
